steps:
  # Lint
  - name: 'golangci/golangci-lint:latest'
    volumes:
      - name: 'go'
        path: '/go'
    env: ['GOPATH=/go']
    args: ['run']

  # Run unit tests
  - name: 'golang:1.24'
    volumes:
      - name: 'go'
        path: '/go'
    env: ['GOPATH=/go']
    args: ['go', 'test', './...']

  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-west1-docker.pkg.dev/gtener-cdks2/cheese-repo/gcp-training-go', '.']

  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-west1-docker.pkg.dev/gtener-cdks2/cheese-repo/gcp-training-go']

  # Deploy to Cloud Run
  - name: 'gcr.io/google-cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'gcp-training-go-service'
      - '--image'
      - 'us-west1-docker.pkg.dev/gtener-cdks2/cheese-repo/gcp-training-go:latest'
      - '--region'
      - 'us-west1'
      - '--allow-unauthenticated'

options:
  logging: 'CLOUD_LOGGING_ONLY'

serviceAccount: 'projects/gtener-cdks2/serviceAccounts/65958498363-compute@developer.gserviceaccount.com'
